### ISSUE TITLE
MinigetError: Status Error 404

### ISSUE THREAD

**Issue by PixelTheDev** [Yonle/qytdl#3]
Hey, this code is amazing and I wanted to test a song for some reasons (make a yt player) with same library as this, and I tried video code `QYh6mYIJG2Y`, and it returns a raw json that says a 404 status. Is this normal, did I do something wrong?

I tried with self host too, not only the pages in readme.

EDIT: Now seems that no video works

**Comment by Yonle** [comment]
@ThePixieDev The code itself is normal. Maybe outdated ytdl

**Comment by Yonle** [comment]
You may need to see [this issue](https://github.com/fent/node-ytdl-core/issues/939) too as it's related with your problem.

**Comment by PixelTheDev** [comment]
> You may need to see [this issue](https://github.com/fent/node-ytdl-core/issues/939) too as it's related with your problem.

Thank you for you fast answer, but in your sites now shows a broken video (tries to play but nothing) and in mine is still a 404 (after ytdl-core update). Any idea?

**Comment by Yonle** [comment]
The only way is waiting for ytdl fix. This because the recent youtube website update with it's endpoint that causes 404 response.

Or, Use [youtube-dl-exec](https://npmjs.com/youtube-dl-exec) for a while

**Comment by PixelTheDev** [comment]
Ok, thank you, closing since is not qytdl issue.

**Comment by Yonle** [comment]
Reopen as this issue still affect everyone.

**Comment by Yonle** [comment]
Closing as it's resolved.
